BASE_URL = "https://www.saucedemo.com/"
username_id = "user-name"
password_id = "password"
login_button_id = "login-button"
item_class_name = "inventory_item_name"
itemPrice_class_name= "inventory_item_price"
errorMessage_xpath = "//*[@id='login_button_container']/div/form/div[3]/h3"
addToCard_xpath= "//*[@id='add-to-cart-test.allthethings()-t-shirt-(red)']"
remove_xpath = "//*[@id='remove-test.allthethings()-t-shirt-(red)']"
productSort_xpath= "//*[@id='header_container']/div[2]/div/span/select"
lowToHigh_xpath= "//*[@id='header_container']/div[2]/div/span/select/option[3]"
invalid_errorMessage = "Epic sadface: Username and password do not match any user in this service"
emptyField_errorMessage = "Epic sadface: Username is required"
emptyPassword_errorMessage = "Epic sadface: Password is required"
lockedOut_errorMessage = "Epic sadface: Sorry, this user has been locked out."
LOGIN_URL = "https://www.saucedemo.com/inventory.html" 